---
- name: Provisioning Server
  hosts: all
  become: yes
  tasks:
    - name: Install packages on CentOS using loops
      yum:
        name: "{{item}}"
        state: present
      when: ansible_distribution == "CentOS"
      loop:
        - ntp
        - wget
        - git
        - zip
        - unzip

    - name: Install NTP on Ubuntu
      apt:
        name: ntp
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Start & Enable NTP on RedHat
      service:
        name: ntpd
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"
      notify:
        - Restart NTP on RedHat
        #calling handler here

    - name: Start & Enable NTP on Debian
      service:
        name: ntp
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"
    
    - name: Add group
      group:
        name: devops
        state: present

    - name: Add users
      user:
        name: "{{item}}"
        state: present
        groups: devops
      loop: "{{usernames}}"

    - name: Dir for dev data
      file:
        path: /opt/devdata
        state: directory
        mode: 0775
      tags:
        - system

    - name: Deploy dev data file
      copy:
        src: files/dev.txt
        dest: /opt/devdata/dev.txt

    handlers:
      - name: Restart NTP on RedHat
        service: 
          name: ntpd
          state: restarted
          enabled: yes
        when: ansible_os_family == "RedHat"
      
      - name: Restart NTP on Debian
        service:
          name: ntp
          state: restarted
          enabled: yes
        when: ansible_os_family == "Debian"
